#' @description Function to write empty tables for CvTdb SQLite file from template docs.
#' @title FUNCTION_TITLE
#' @return OUTPUT_DESCRIPTION
#' @details DETAILS
#' @examples 
#' \dontrun{
#' if(interactive()){
#'  #EXAMPLE1
#'  }
#' }
#' @rdname db_initialize_CvTdb
#' @export 
db_initialize_CvTdb <- function(){
  db_push_tbl_to_db(dat=data.frame(id=as.numeric(),
                                pmid=as.character(),
                                other_study_identifier=as.character(),
                                doi=as.character(),
                                first_author=as.character(),
                                year=as.character(),
                                title=as.character(),
                                url=as.character(),
                                curator_comment=as.character()),
                 tblName="Documents",
                 overwrite=TRUE,
                 fieldTypes = c(id="INTEGER PRIMARY KEY AUTOINCREMENT",
                                pmid="varchar(25)",
                                other_study_identifier="varchar(100)",
                                doi="varchar(100)",
                                first_author="varchar(100)",
                                year="varchar(20)",
                                title="varchar(250)",
                                url="varchar(200)",
                                curator_comment="varchar(250)"))
  
  db_push_tbl_to_db(dat = data.frame(id=as.numeric(),
                                  fk_extraction_document_id=as.character(),
                                  test_substance_name=as.character(),
                                  dose_level=as.character(),
                                  dose_level_units=as.character(),
                                  administration_route=as.character(),
                                  dose_duration=as.character(),
                                  dose_frequency=as.character(),
                                  dose_vehicle=as.character(),
                                  dose_volume=as.character(),
                                  fasting_period=as.character(),
                                  author_comment=as.character(),
                                  curator_comment=as.character(),
                                  dermal_dose_vehicle=as.character(),
                                  dermal_dose_vehicle_pH=as.character(),
                                  dermal_applied_area=as.character(),
                                  dermal_applied_area_units=as.character(),
                                  aerosol_particle_diameter_mean=as.character(),
                                  aerosol_particle_diameter_gsd=as.character(),
                                  aerosol_particle_diameter_units=as.character(),
                                  aerosol_particle_density=as.character(),
                                  aerosol_particle_density_units=as.character()),
                 tblName="Studies",
                 overwrite=TRUE,
                 fieldTypes = c(id="INTEGER PRIMARY KEY AUTOINCREMENT",
                                fk_extraction_document_id="varchar(25)",
                                test_substance_name="varchar(100)",
                                dose_level="varchar(100)",
                                dose_level_units="varchar(100)",
                                administration_route="varchar(100)",
                                dose_duration="varchar(100)",
                                dose_frequency="varchar(100)",
                                dose_vehicle="varchar(100)",
                                dose_volume="varchar(100)",
                                fasting_period="varchar(100)",
                                author_comment="varchar(250)",
                                curator_comment="varchar(100)",
                                dermal_dose_vehicle="varchar(100)",
                                dermal_dose_vehicle_pH="varchar(100)",
                                dermal_applied_area="varchar(100)",
                                dermal_applied_area_units="varchar(100)",
                                aerosol_particle_diameter_mean="varchar(100)",
                                aerosol_particle_diameter_gsd="varchar(100)",
                                aerosol_particle_diameter_units="varchar(100)",
                                aerosol_particle_density="varchar(100)",
                                aerosol_particle_density_units="varchar(100)")
  )
  
  db_push_tbl_to_db(dat= data.frame(id=as.numeric(),
                                 species=as.character(),
                                 subtype=as.character(),
                                 sex=as.character(),	
                                 age=as.character(),
                                 age_category=as.character(),
                                 height=as.character(),
                                 weight=as.character(),
                                 curator_comment=as.character()),
                 tblName="Subjects",
                 overwrite=TRUE,
                 fieldTypes = c(id="INTEGER PRIMARY KEY AUTOINCREMENT",
                                species="varchar(100)",
                                subtype="varchar(100)",
                                sex="varchar(100)",	
                                age="varchar(100)",
                                age_category="varchar(100)",
                                height="varchar(100)",
                                weight="varchar(100)",
                                curator_comment="varchar(100)"))
  
  db_push_tbl_to_db(dat=data.frame(id=as.numeric(),
                                analyte_name=as.character(),
                                figure_name=as.character(),
                                figure_type=as.character(),
                                figure_series_identifier=as.character(),
                                x_min=as.character(),
                                x_max=as.character(),
                                y_min=as.character(),
                                y_max=as.character(),
                                time_units=as.character(),
                                conc_units=as.character(),
                                log_conc_units=as.character(),
                                loq=as.character(),
                                loq_units=as.character(),
                                lod=as.character(),
                                lod_units=as.character(),
                                analytical_method_detail=as.character(),
                                radiolabeled=as.character(),
                                fk_study_id=as.numeric(),
                                fk_subject_id=as.numeric(),
                                n_subjects_in_series=as.character(),
                                conc_medium=as.character(),
                                curator_comment=as.character()),
                 tblName="Series",
                 overwrite=TRUE,
                 fieldTypes =c(id="INTEGER PRIMARY KEY AUTOINCREMENT",
                               analyte_name="varchar(100)",
                               figure_type="varchar(100)",
                               figure_name="varchar(100)",
                               figure_series_identifier="varchar(100)",
                               x_min="varchar(50)",
                               x_max="varchar(50)",
                               y_min="varchar(50)",
                               y_max="varchar(50)",
                               time_units="varchar(100)",
                               conc_units="varchar(100)",
                               log_conc_units="varchar(100)",
                               loq="varchar(100)",
                               loq_units="varchar(100)",
                               lod="varchar(100)",
                               lod_units="varchar(100)",
                               analytical_method_detail="varchar(100)",
                               radiolabeled="varchar(100)",
                               fk_study_id="INTEGER",
                               fk_subject_id="INTEGER",
                               n_subjects_in_series="varchar(100)",
                               conc_medium="varchar(100)",
                               curator_comment="varchar(100)"))
  
  db_push_tbl_to_db(dat=data.frame(id=as.numeric(),
                                fk_series_id=as.numeric(),
                                time=as.character(),
                                conc=as.character(),
                                conc_sd=as.character(),
                                conc_lower_bound=as.character(),
                                conc_upper_bound=as.character(),
                                curator_comment=as.character()),
                 tblName="Conc_Time_Values",
                 overwrite=TRUE,
                 fieldTypes=c(id="INTEGER PRIMARY KEY AUTOINCREMENT",
                              fk_series_id="INTEGER",
                              time="varchar(100)",
                              conc="varchar(100)",
                              conc_sd="varchar(100)",
                              conc_lower_bound="varchar(100)",
                              conc_upper_bound="varchar(100)",
                              curator_comment="varchar(100)"))
  
}
