rules:
- expr: 'if (!is.na(id)) !is.na(as.numeric(gsub("QC_", "", id)))'
  meta:
    message: invalid_field_type_id
- expr: 'if (!is.na(fk_series_id)) !is.na(as.numeric(gsub("QC_", "", fk_series_id)))'
  meta:
    message: invalid_field_type_fk_series_id
- expr: 'if (!is.na(time)) !is.na(as.numeric(gsub("[.]", "", time)))'
  meta:
    message: invalid_field_type_time
- expr: 'if (!is.na(conc_bound_type)) is.na(as.numeric(conc_bound_type))'
  meta:
    message: invalid_field_type_conc_bound_type
